### ISSUE TITLE
Logstash appender fallback broken on ColdBox 7

### ISSUE THREAD

**Issue by michaelborn** [coldbox-modules/cbelasticsearch#130]
See this partial stack trace:

```
lucee.runtime.exp.ExpressionException: The parameter [appenders] to function [getAppendersMap] is required but was not passed in.
	at lucee.runtime.type.UDFImpl.defineArguments(UDFImpl.java:143)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:347)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:223)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:698)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:586)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1933)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:787)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1775)
	at models.logging.logstashappender_cfc$cf.udfCall1(/cbElasticsearch/models/logging/LogstashAppender.cfc:160)
	at models.logging.logstashappender_cfc$cf.udfCall(/cbElasticsearch/models/logging/LogstashAppender.cfc)
```

Looks like the `getAppendersMap()` call in `LogstashAppender.cfc` is missing the required `appenders` parameter.

```
var appendersMap  = application.wirebox.getLogbox().getAppendersMap();
```

Should be:

```
var appendersMap  = application.wirebox.getLogbox().getAppendersMap(
	application.wirebox.getLogbox().getConfig().getRoot().appenders
);
```

**Comment by michaelborn** [comment]
Looks like this was resolved in `v3.2.5`:

https://github.com/coldbox-modules/cbelasticsearch/commit/9cbee136248fed0409d5589e3677a4f23a0a5b84
